server:
  port: 0

spring:
  application:
    name: product-microservice
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092,localhost:9094
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: all
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
